#! /usr/bin/env python3

import argparse

import gceditcli


if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--display-progress', action='store_true')

    subparsers = parser.add_subparsers()
    for c in gceditcli.command.all_commands:
        c().init(subparsers)
    args = parser.parse_args()
    if hasattr(args, 'execute'):
        args.execute(args)
    else:
        parser.error('expected COMMAND argument')
