#! /usr/bin/env python

# script for building and installing the Python package

from distutils.core import setup

setup(name = 'gcedit', version = '0.1-dev',
      packages = ['gcedit', 'gcedit.ext'])